vms:
  hosts:
    ansible1:
      ansible_ssh_host: 10.5.13.10
      ansible_ssh_pass: "Administrator1!"
      ansible_ssh_user: "it-administrator"
      ansible_python_interpreter: /usr/bin/python3
    ansible2:
      ansible_ssh_host: 10.5.13.11
      ansible_ssh_pass: "Administrator1!"
      ansible_ssh_user: "it-administrator"
      ansible_python_interpreter: /usr/bin/python3
    ansible3:
      ansible_ssh_host: 10.5.13.12
      ansible_ssh_pass: "Administrator1!"
      ansible_ssh_user: "it-administrator"
      ansible_python_interpreter: /usr/bin/python3


